# importing dependencies

In [337]:
import numpy as np
import pandas as pd

# loading dataset

In [338]:
movies_df = pd.read_csv("movies.csv")
credits_df = pd.read_csv("credits.csv")

# checkfing contents of movies_df

In [339]:
movies_df.head(20)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
5,258000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...",http://www.sonypictures.com/movies/spider-man3/,559,"[{""id"": 851, ""name"": ""dual identity""}, {""id"": ...",en,Spider-Man 3,The seemingly invincible Spider-Man goes up ag...,115.699814,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-01,890871626,139.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The battle within.,Spider-Man 3,5.9,3576
6,260000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",http://disney.go.com/disneypictures/tangled/,38757,"[{""id"": 1562, ""name"": ""hostage""}, {""id"": 2343,...",en,Tangled,When the kingdom's most wanted-and most charmi...,48.681969,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2010-11-24,591794936,100.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They're taking adventure to new lengths.,Tangled,7.4,3330
7,280000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://marvel.com/movies/movie/193/avengers_ag...,99861,"[{""id"": 8828, ""name"": ""marvel comic""}, {""id"": ...",en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,134.279229,"[{""name"": ""Marvel Studios"", ""id"": 420}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-04-22,1405403694,141.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Age Has Come.,Avengers: Age of Ultron,7.3,6767
8,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://harrypotter.warnerbros.com/harrypottera...,767,"[{""id"": 616, ""name"": ""witch""}, {""id"": 2343, ""n...",en,Harry Potter and the Half-Blood Prince,"As Harry begins his sixth year at Hogwarts, he...",98.885637,"[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2009-07-07,933959197,153.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Dark Secrets Revealed,Harry Potter and the Half-Blood Prince,7.4,5293
9,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.batmanvsupermandawnofjustice.com/,209112,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 7002...",en,Batman v Superman: Dawn of Justice,Fearing the actions of a god-like Super Hero l...,155.790452,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""A...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-03-23,873260194,151.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Justice or revenge,Batman v Superman: Dawn of Justice,5.7,7004
10,270000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://www.superman.com,1452,"[{""id"": 83, ""name"": ""saving the world""}, {""id""...",en,Superman Returns,Superman returns to discover his 5-year absenc...,57.925623,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""L...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2006-06-28,391081192,154.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,NaN,Superman Returns,5.4,1400
11,200000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",http://www.mgm.com/view/movie/234/Quantum-of-S...,10764,"[{""id"": 627, ""name"": ""killing""}, {""id"": 1568, ...",en,Quantum of Solace,Quantum of Solace continues the adventures of ...,107.928811,"[{""name"": ""Eon Productions"", ""id"": 7576}]","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2008-10-30,586090727,106.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,"For love, for hate, for justice, for revenge.",Quantum of Solace,6.1,2965
12,200000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,58,"[{""id"": 616, ""name"": ""witch""}, {""id"": 663, ""na...",en,Pirates of the Caribbean: Dead Man's Chest,Captain Jack Sparrow works his way out of a bl...,145.847379,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""JM"", ""name"": ""Jamaica""}, {""is...",2006-06-20,1065659812,151.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Jack is back!,Pirates of the Caribbean: Dead Man's Chest,7.0,5246
13,255000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://disney.go.com/the-lone-ranger/,57201,"[{""id"": 1556, ""name"": ""texas""}, {""id"": 2673, ""...",en,The Lone Ranger,The Texas Rangers chase down a gang of outlaws...,49.046956,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-07-03,89289910,149.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Never Take Off the Mask,The Lone Ranger,5.9,2311
14,225000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.manofsteel.com/,49521,"[{""id"": 83, ""name"": ""saving the world""}, {""id""...",en,Man of Steel,A young boy learns that he has extraordinary p...,99.398009,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2013-06-12,662845518,143.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,You will believe that a man can fly.,Man of Steel,6.5,6359
15,225000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 10751...",NaN,2454,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,The Chronicles of Narnia: Prince Caspian,One year after their incredible adventures in ...,53.978602,"[{""name"": ""Walt Disney"", ""id"": 5888}, {""name"":...","[{""iso_3166_1"": ""CZ"", ""name"": ""Czech Republic""...",2008-05-15,419651413,150.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Hope has a new face.,The Chronicles of Narnia: Prince Caspian,6.3,1630
16,220000000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",http://marvel.com/avengers_movie/,24428,"[{""id"": 242, ""name"": ""new york""}, {""id"": 5539,...",en,The Avengers,When an unexpected enemy emerges and threatens...,144.448633,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-04-25,1519557910,143.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Some assembly required.,The Avengers,7.4,11776
17,380000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",http://disney.go.com/pirates/index-on-stranger...,1865,"[{""id"": 658, ""name"": ""sea""}, {""id"": 1316, ""nam...",en,Pirates of the Caribbean: On Stranger Tides,Captain Jack Sparrow crosses paths with a woma...,135.413856,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2011-05-14,1045713802,136.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Live Forever Or Die Trying.,Pirates of the Caribbean: On Stranger Tides,6.4,4948
18,225000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 35, ""nam...",http://www.sonypictures.com/movies/meninblack3/,41154,"[{""id"": 4379, ""name"": ""time travel""}, {""id"": 5...",en,Men in Black 3,Agents J (Will Smith) and K (Tommy Lee Jones) ...,52.035179,"[{""name"": ""Amblin Entertainment"", ""id"": 56}, {...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-23,624026776,106.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They are back... in time.,Men in Black 3,6.2,4160
19,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.thehobbit.com/,122917,"[{""id"": 417, ""name"": ""corruption""}, {""id"": 603...",en,The Hobbit: The Battle of the Five Armies,Immediately after the events of The Desolation...,120.965743,"[{""name"": ""WingNut Films"", ""id"": 11}, {""name"":...","[{""iso_3166_1"": ""NZ"", ""name"": ""New Zealand""}, ...",2014-12-10,956019788,144.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Witness the defining chapter of the Middle-Ear...,The Hobbit: The Battle of the Five Armies,7.1,4760

In [340]:
credits_df.head(20)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
5,559,Spider-Man 3,"[{""cast_id"": 30, ""character"": ""Peter Parker / ...","[{""credit_id"": ""52fe4252c3a36847f80151a5"", ""de..."
6,38757,Tangled,"[{""cast_id"": 34, ""character"": ""Flynn Rider (vo...","[{""credit_id"": ""52fe46db9251416c91062101"", ""de..."
7,99861,Avengers: Age of Ultron,"[{""cast_id"": 76, ""character"": ""Tony Stark / Ir...","[{""credit_id"": ""55d5f7d4c3a3683e7e0016eb"", ""de..."
8,767,Harry Potter and the Half-Blood Prince,"[{""cast_id"": 3, ""character"": ""Harry Potter"", ""...","[{""credit_id"": ""52fe4273c3a36847f801fab1"", ""de..."
9,209112,Batman v Superman: Dawn of Justice,"[{""cast_id"": 18, ""character"": ""Bruce Wayne / B...","[{""credit_id"": ""553bf23692514135c8002886"", ""de..."
10,1452,Superman Returns,"[{""cast_id"": 3, ""character"": ""Superman / Clark...","[{""credit_id"": ""553bef6a9251416874003c8f"", ""de..."
11,10764,Quantum of Solace,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""52fe43b29251416c7501aa63"", ""de..."
12,58,Pirates of the Caribbean: Dead Man's Chest,"[{""cast_id"": 37, ""character"": ""Captain Jack Sp...","[{""credit_id"": ""52fe4211c3a36847f8001873"", ""de..."
13,57201,The Lone Ranger,"[{""cast_id"": 4, ""character"": ""Tonto"", ""credit_...","[{""credit_id"": ""52fe4928c3a36847f818be95"", ""de..."
14,49521,Man of Steel,"[{""cast_id"": 2, ""character"": ""Clark Kent / Kal...","[{""credit_id"": ""52fe4799c3a36847f813e667"", ""de..."
15,2454,The Chronicles of Narnia: Prince Caspian,"[{""cast_id"": 1, ""character"": ""Prince Caspian"",...","[{""credit_id"": ""55a239e69251412979002e8b"", ""de..."
16,24428,The Avengers,"[{""cast_id"": 46, ""character"": ""Tony Stark / Ir...","[{""credit_id"": ""52fe4495c3a368484e02b1cf"", ""de..."
17,1865,Pirates of the Caribbean: On Stranger Tides,"[{""cast_id"": 15, ""character"": ""Captain Jack Sp...","[{""credit_id"": ""566b4f54c3a3683f56005151"", ""de..."
18,41154,Men in Black 3,"[{""cast_id"": 4, ""character"": ""Agent J"", ""credi...","[{""credit_id"": ""52fe45b7c3a36847f80d68c7"", ""de..."
19,122917,The Hobbit: The Battle of the Five Armies,"[{""cast_id"": 10, ""character"": ""Bilbo Baggins"",...","[{""credit_id"": ""548ad49a9251414fa20011ab"", ""de..."

In [341]:
# checking data

In [342]:
print("MOVIES")
print("Null data ", movies_df.isnull().sum())
print("\nDuplicated data: ", movies_df.duplicated().sum())
print("\n"+"="*20)
print("\nCREDIT")
print("Null data ", credits_df.isnull().sum())
print("\nDuplicated data: ", credits_df.duplicated().sum())

MOVIES
Null data  budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

Duplicated data:  0

====================

CREDIT
Null data  movie_id    0
title       0
cast        0
crew        0
dtype: int64

Duplicated data:  0

In [343]:
movies_df = movies_df.drop(columns=['homepage'])

In [344]:
# check if homepage gone.

In [345]:
movies_df.head(20)

,budget,genres,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
5,258000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...",559,"[{""id"": 851, ""name"": ""dual identity""}, {""id"": ...",en,Spider-Man 3,The seemingly invincible Spider-Man goes up ag...,115.699814,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-01,890871626,139.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The battle within.,Spider-Man 3,5.9,3576
6,260000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",38757,"[{""id"": 1562, ""name"": ""hostage""}, {""id"": 2343,...",en,Tangled,When the kingdom's most wanted-and most charmi...,48.681969,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2010-11-24,591794936,100.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They're taking adventure to new lengths.,Tangled,7.4,3330
7,280000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",99861,"[{""id"": 8828, ""name"": ""marvel comic""}, {""id"": ...",en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,134.279229,"[{""name"": ""Marvel Studios"", ""id"": 420}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-04-22,1405403694,141.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Age Has Come.,Avengers: Age of Ultron,7.3,6767
8,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",767,"[{""id"": 616, ""name"": ""witch""}, {""id"": 2343, ""n...",en,Harry Potter and the Half-Blood Prince,"As Harry begins his sixth year at Hogwarts, he...",98.885637,"[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2009-07-07,933959197,153.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Dark Secrets Revealed,Harry Potter and the Half-Blood Prince,7.4,5293
9,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",209112,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 7002...",en,Batman v Superman: Dawn of Justice,Fearing the actions of a god-like Super Hero l...,155.790452,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""A...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-03-23,873260194,151.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Justice or revenge,Batman v Superman: Dawn of Justice,5.7,7004
10,270000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",1452,"[{""id"": 83, ""name"": ""saving the world""}, {""id""...",en,Superman Returns,Superman returns to discover his 5-year absenc...,57.925623,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""L...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2006-06-28,391081192,154.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,NaN,Superman Returns,5.4,1400
11,200000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",10764,"[{""id"": 627, ""name"": ""killing""}, {""id"": 1568, ...",en,Quantum of Solace,Quantum of Solace continues the adventures of ...,107.928811,"[{""name"": ""Eon Productions"", ""id"": 7576}]","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2008-10-30,586090727,106.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,"For love, for hate, for justice, for revenge.",Quantum of Solace,6.1,2965
12,200000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",58,"[{""id"": 616, ""name"": ""witch""}, {""id"": 663, ""na...",en,Pirates of the Caribbean: Dead Man's Chest,Captain Jack Sparrow works his way out of a bl...,145.847379,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""JM"", ""name"": ""Jamaica""}, {""is...",2006-06-20,1065659812,151.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Jack is back!,Pirates of the Caribbean: Dead Man's Chest,7.0,5246
13,255000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",57201,"[{""id"": 1556, ""name"": ""texas""}, {""id"": 2673, ""...",en,The Lone Ranger,The Texas Rangers chase down a gang of outlaws...,49.046956,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-07-03,89289910,149.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Never Take Off the Mask,The Lone Ranger,5.9,2311
14,225000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49521,"[{""id"": 83, ""name"": ""saving the world""}, {""id""...",en,Man of Steel,A young boy learns that he has extraordinary p...,99.398009,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2013-06-12,662845518,143.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,You will believe that a man can fly.,Man of Steel,6.5,6359
15,225000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 10751...",2454,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,The Chronicles of Narnia: Prince Caspian,One year after their incredible adventures in ...,53.978602,"[{""name"": ""Walt Disney"", ""id"": 5888}, {""name"":...","[{""iso_3166_1"": ""CZ"", ""name"": ""Czech Republic""...",2008-05-15,419651413,150.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Hope has a new face.,The Chronicles of Narnia: Prince Caspian,6.3,1630
16,220000000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",24428,"[{""id"": 242, ""name"": ""new york""}, {""id"": 5539,...",en,The Avengers,When an unexpected enemy emerges and threatens...,144.448633,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-04-25,1519557910,143.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Some assembly required.,The Avengers,7.4,11776
17,380000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",1865,"[{""id"": 658, ""name"": ""sea""}, {""id"": 1316, ""nam...",en,Pirates of the Caribbean: On Stranger Tides,Captain Jack Sparrow crosses paths with a woma...,135.413856,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2011-05-14,1045713802,136.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Live Forever Or Die Trying.,Pirates of the Caribbean: On Stranger Tides,6.4,4948
18,225000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 35, ""nam...",41154,"[{""id"": 4379, ""name"": ""time travel""}, {""id"": 5...",en,Men in Black 3,Agents J (Will Smith) and K (Tommy Lee Jones) ...,52.035179,"[{""name"": ""Amblin Entertainment"", ""id"": 56}, {...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-23,624026776,106.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They are back... in time.,Men in Black 3,6.2,4160
19,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",122917,"[{""id"": 417, ""name"": ""corruption""}, {""id"": 603...",en,The Hobbit: The Battle of the Five Armies,Immediately after the events of The Desolation...,120.965743,"[{""name"": ""WingNut Films"", ""id"": 11}, {""name"":...","[{""iso_3166_1"": ""NZ"", ""name"": ""New Zealand""}, ...",2014-12-10,956019788,144.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Witness the defining chapter of the Middle-Ear...,The Hobbit: The Battle of the Five Armies,7.1,4760

In [346]:
# fill mean value to release date and runime

In [347]:
movies_df['runtime'] = movies_df['runtime'].fillna(movies_df['runtime'].mean())

In [348]:
movies_df[['overview', 'tagline']] = movies_df[['overview', 'tagline']].fillna("")

In [349]:
movies_df.drop(columns=['release_date', 'budget', 'original_language', 'original_title', 'status', 'production_countries'],inplace=True)

In [350]:
print(movies_df.columns)

Index(['genres', 'id', 'keywords', 'overview', 'popularity',
       'production_companies', 'revenue', 'runtime', 'spoken_languages',
       'tagline', 'title', 'vote_average', 'vote_count'],
      dtype='str')

In [351]:
print("AFTER:\nMOVIES")
print("Null data \n", movies_df.isnull().sum())
print("\nDuplicated data: ", movies_df.duplicated().sum())
print("\n"+"="*20)
print("\nCREDIT")
print("Null data ", credits_df.isnull().sum())
print("\nDuplicated data: ", credits_df.duplicated().sum())

AFTER:
MOVIES
Null data
 genres                  0
id                      0
keywords                0
overview                0
popularity              0
production_companies    0
revenue                 0
runtime                 0
spoken_languages        0
tagline                 0
title                   0
vote_average            0
vote_count              0
dtype: int64

Duplicated data:  0

====================

CREDIT
Null data  movie_id    0
title       0
cast        0
crew        0
dtype: int64

Duplicated data:  0

In [352]:
movies_df['genres'].head(20)

0     [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1     [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2     [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3     [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4     [{"id": 28, "name": "Action"}, {"id": 12, "nam...
5     [{"id": 14, "name": "Fantasy"}, {"id": 28, "na...
6     [{"id": 16, "name": "Animation"}, {"id": 10751...
7     [{"id": 28, "name": "Action"}, {"id": 12, "nam...
8     [{"id": 12, "name": "Adventure"}, {"id": 14, "...
9     [{"id": 28, "name": "Action"}, {"id": 12, "nam...
10    [{"id": 12, "name": "Adventure"}, {"id": 14, "...
11    [{"id": 12, "name": "Adventure"}, {"id": 28, "...
12    [{"id": 12, "name": "Adventure"}, {"id": 14, "...
13    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
14    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
15    [{"id": 12, "name": "Adventure"}, {"id": 10751...
16    [{"id": 878, "name": "Science Fiction"}, {"id"...
17    [{"id": 12, "name": "Adventure"}, {"id": 28, "...
18    [{"id": 28, "name": "Action"}, {"id": 35, "nam...
19    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
Name: genres, dtype: str

In [353]:
## Flattening dictionary to string

In [354]:
import ast
def removeDictionary(dictString: str):
    try:
        dict_list = ast.literal_eval(dictString)
        lists = []
        for i in dict_list:
            lists.append(i["name"].replace(" ", ""))
        return " ".join(lists)
    except:
        return dictString

In [355]:
movies_df[['genres', 'keywords', 'production_companies', 'spoken_languages']] = movies_df[['genres', 'keywords', 'production_companies', 'spoken_languages']].map(removeDictionary)

In [356]:
credits_df[['cast', 'crew']] = credits_df[['cast', 'crew']].map(removeDictionary)

In [357]:
movies_df.head(20)

,genres,id,keywords,overview,popularity,production_companies,revenue,runtime,spoken_languages,tagline,title,vote_average,vote_count
0,Action Adventure Fantasy ScienceFiction,19995,cultureclash future spacewar spacecolony socie...,"In the 22nd century, a paraplegic Marine is di...",150.437577,IngeniousFilmPartners TwentiethCenturyFoxFilmC...,2787965087,162.0,English Español,Enter the World of Pandora.,Avatar,7.2,11800
1,Adventure Fantasy Action,285,ocean drugabuse exoticisland eastindiatradingc...,"Captain Barbossa, long believed to be dead, ha...",139.082615,WaltDisneyPictures JerryBruckheimerFilms Secon...,961000000,169.0,English,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,Action Adventure Crime,206647,spy basedonnovel secretagent sequel mi6 britis...,A cryptic message from Bond’s past sends him o...,107.376788,ColumbiaPictures Danjaq B24,880674609,148.0,Français English Español Italiano Deutsch,A Plan No One Escapes,Spectre,6.3,4466
3,Action Crime Drama Thriller,49026,dccomics crimefighter terrorist secretidentity...,Following the death of District Attorney Harve...,112.312950,LegendaryPictures WarnerBros. DCEntertainment ...,1084939099,165.0,English,The Legend Ends,The Dark Knight Rises,7.6,9106
4,Action Adventure ScienceFiction,49529,basedonnovel mars medallion spacetravel prince...,"John Carter is a war-weary, former military ca...",43.926995,WaltDisneyPictures,284139100,132.0,English,"Lost in our world, found in another.",John Carter,6.1,2124
5,Fantasy Action Adventure,559,dualidentity amnesia sandstorm loveofone'slife...,The seemingly invincible Spider-Man goes up ag...,115.699814,ColumbiaPictures LauraZiskinProductions Marvel...,890871626,139.0,English Français,The battle within.,Spider-Man 3,5.9,3576
6,Animation Family,38757,hostage magic horse fairytale musical princess...,When the kingdom's most wanted-and most charmi...,48.681969,WaltDisneyPictures WaltDisneyAnimationStudios,591794936,100.0,English,They're taking adventure to new lengths.,Tangled,7.4,3330
7,Action Adventure ScienceFiction,99861,marvelcomic sequel superhero basedoncomicbook ...,When Tony Stark tries to jumpstart a dormant p...,134.279229,MarvelStudios PrimeFocus RevolutionSunStudios,1405403694,141.0,English,A New Age Has Come.,Avengers: Age of Ultron,7.3,6767
8,Adventure Fantasy Family,767,witch magic broom schoolofwitchcraft wizardry ...,"As Harry begins his sixth year at Hogwarts, he...",98.885637,WarnerBros. HeydayFilms,933959197,153.0,English,Dark Secrets Revealed,Harry Potter and the Half-Blood Prince,7.4,5293
9,Action Adventure Fantasy,209112,dccomics vigilante superhero basedoncomicbook ...,Fearing the actions of a god-like Super Hero l...,155.790452,DCComics AtlasEntertainment WarnerBros. DCEnte...,873260194,151.0,English,Justice or revenge,Batman v Superman: Dawn of Justice,5.7,7004
10,Adventure Fantasy Action ScienceFiction,1452,savingtheworld dccomics invulnerability sequel...,Superman returns to discover his 5-year absenc...,57.925623,DCComics LegendaryPictures WarnerBros. BadHatH...,391081192,154.0,English Français Deutsch,,Superman Returns,5.4,1400
11,Adventure Action Thriller Crime,10764,killing undercover secretagent britishsecretse...,Quantum of Solace continues the adventures of ...,107.928811,EonProductions,586090727,106.0,English Español Italiano Français Deutsch,"For love, for hate, for justice, for revenge.",Quantum of Solace,6.1,2965
12,Adventure Fantasy Action,58,witch fortuneteller bondage exoticisland monst...,Captain Jack Sparrow works his way out of a bl...,145.847379,WaltDisneyPictures JerryBruckheimerFilms Secon...,1065659812,151.0,English Türkçe ελληνικά 普通话,Jack is back!,Pirates of the Caribbean: Dead Man's Chest,7.0,5246
13,Action Adventure Western,57201,texas horse survivor texasranger partner outla...,The Texas Rangers chase down a gang of outlaws...,49.046956,WaltDisneyPictures JerryBruckheimerFilms Infin...,89289910,149.0,English,Never Take Off the Mask,The Lone Ranger,5.9,2311
14,Action Adventure Fantasy ScienceFiction,49521,savingtheworld dccomics superhero basedoncomic...,A young boy learns that he has extraordinary p...,99.398009,LegendaryPictures WarnerBros. DCEntertainment ...,662845518,143.0,English,You will believe that a man can fly.,Man of Steel,6.5,6359
15,Adventure Family Fantasy,2454,basedonnovel fictionalplace brothersisterrelat...,One year after their incredible adventures in ...,53.978602,WaltDisney WaldenMedia StillkingFilms OzumiFil...,419651413,150.0,English,Hope has a new face.,The Chronicles of Narnia: Prince Caspian,6.3,1630
16,ScienceFiction Action Adventure,24428,newyork shield marvelcomic superhero basedonco...,When an unexpected enemy emerges and threatens...,144.448633,ParamountPictures MarvelStudios,1519557910,143.0,English,Some assembly required.,The Avengers,7.4,11776
17,Adventure Action Fantasy,1865,sea captain mutiny sword primeminister sailing...,Captain Jack Sparrow crosses paths with a woma...,135.413856,WaltDisneyPictures JerryBruckheimerFilms Movin...,1045713802,136.0,English Español,Live Forever Or Die Trying.,Pirates of the Caribbean: On Stranger Tides,6.4,4948
18,Action Comedy ScienceFiction,41154,timetravel timemachine alien fictionalgovernme...,Agents J (Will Smith) and K (Tommy Lee Jones) ...,52.035179,AmblinEntertainment MediaMagikEntertainment Im...,624026776,106.0,English,They are back... in time.,Men in Black 3,6.2,4160
19,Action Adventure Fantasy,122917,corruption elves dwarves orcs middle-earth(tol...,Immediately after the events of The Desolation...,120.965743,WingNutFilms NewLineCinema WarnerBros.Pictures...,956019788,144.0,English,Witness the defining chapter of the Middle-Ear...,The Hobbit: The Battle of the Five Armies,7.1,4760

In [358]:
credits_df.head(20)

,movie_id,title,cast,crew
0,19995,Avatar,SamWorthington ZoeSaldana SigourneyWeaver Step...,StephenE.Rivkin RickCarter ChristopherBoyes Ch...
1,285,Pirates of the Caribbean: At World's End,JohnnyDepp OrlandoBloom KeiraKnightley Stellan...,DariuszWolski GoreVerbinski JerryBruckheimer T...
2,206647,Spectre,DanielCraig ChristophWaltz LéaSeydoux RalphFie...,ThomasNewman SamMendes AnnaPinnock JohnLogan J...
3,49026,The Dark Knight Rises,ChristianBale MichaelCaine GaryOldman AnneHath...,HansZimmer CharlesRoven ChristopherNolan Chris...
4,49529,John Carter,TaylorKitsch LynnCollins SamanthaMorton Willem...,AndrewStanton AndrewStanton JohnLasseter Colin...
5,559,Spider-Man 3,TobeyMaguire KirstenDunst JamesFranco ThomasHa...,FrancineMaisler JosephM.CaraccioloJr. SamRaimi...
6,38757,Tangled,ZacharyLevi MandyMoore DonnaMurphy RonPerlman ...,JohnLasseter JacobGrimm WilhelmGrimm JohnKahrs...
7,99861,Avengers: Age of Ultron,RobertDowneyJr. ChrisHemsworth MarkRuffalo Chr...,DannyElfman ChristopherBoyes ChristopherBoyes ...
8,767,Harry Potter and the Half-Blood Prince,DanielRadcliffe RupertGrint EmmaWatson TomFelt...,BrunoDelbonnel StephanieMcMillan StuartCraig J...
9,209112,Batman v Superman: Dawn of Justice,BenAffleck HenryCavill GalGadot AmyAdams Jesse...,HansZimmer CharlesRoven ChristopherNolan EmmaT...
10,1452,Superman Returns,BrandonRouth KevinSpacey KateBosworth JamesMar...,RogerMussenden JonPeters DianeMacke GilbertAdl...
11,10764,Quantum of Solace,DanielCraig OlgaKurylenko MathieuAmalric JudiD...,PaulHaggis DennisGassner IanFleming LouiseFrog...
12,58,Pirates of the Caribbean: Dead Man's Chest,JohnnyDepp OrlandoBloom KeiraKnightley Stellan...,DariuszWolski GoreVerbinski JerryBruckheimer T...
13,57201,The Lone Ranger,JohnnyDepp ArmieHammer WilliamFichtner HelenaB...,GoreVerbinski GoreVerbinski JerryBruckheimer T...
14,49521,Man of Steel,HenryCavill AmyAdams MichaelShannon KevinCostn...,HansZimmer CharlesRoven LloydPhillips Christop...
15,2454,The Chronicles of Narnia: Prince Caspian,BenBarnes WilliamMoseley AnnaPopplewell Skanda...,LizMullane GailStevens DavidMinkowski MatthewS...
16,24428,The Avengers,RobertDowneyJr. ChrisEvans MarkRuffalo ChrisHe...,AlanSilvestri ChristopherBoyes ChristopherBoye...
17,1865,Pirates of the Caribbean: On Stranger Tides,JohnnyDepp PenélopeCruz IanMcShane KevinMcNall...,DariuszWolski JerryBruckheimer TedElliott Terr...
18,41154,Men in Black 3,WillSmith TommyLeeJones JoshBrolin MichaelStuh...,StevenSpielberg DannyElfman EllenChenoweth Wal...
19,122917,The Hobbit: The Battle of the Five Armies,MartinFreeman IanMcKellen RichardArmitage KenS...,HowardShore ChristopherBoyes PeterJackson Pete...

In [359]:
df = movies_df.merge(credits_df, on="title")

In [360]:
df.head(20)

,genres,id,keywords,overview,popularity,production_companies,revenue,runtime,spoken_languages,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,Action Adventure Fantasy ScienceFiction,19995,cultureclash future spacewar spacecolony socie...,"In the 22nd century, a paraplegic Marine is di...",150.437577,IngeniousFilmPartners TwentiethCenturyFoxFilmC...,2787965087,162.0,English Español,Enter the World of Pandora.,Avatar,7.2,11800,19995,SamWorthington ZoeSaldana SigourneyWeaver Step...,StephenE.Rivkin RickCarter ChristopherBoyes Ch...
1,Adventure Fantasy Action,285,ocean drugabuse exoticisland eastindiatradingc...,"Captain Barbossa, long believed to be dead, ha...",139.082615,WaltDisneyPictures JerryBruckheimerFilms Secon...,961000000,169.0,English,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,JohnnyDepp OrlandoBloom KeiraKnightley Stellan...,DariuszWolski GoreVerbinski JerryBruckheimer T...
2,Action Adventure Crime,206647,spy basedonnovel secretagent sequel mi6 britis...,A cryptic message from Bond’s past sends him o...,107.376788,ColumbiaPictures Danjaq B24,880674609,148.0,Français English Español Italiano Deutsch,A Plan No One Escapes,Spectre,6.3,4466,206647,DanielCraig ChristophWaltz LéaSeydoux RalphFie...,ThomasNewman SamMendes AnnaPinnock JohnLogan J...
3,Action Crime Drama Thriller,49026,dccomics crimefighter terrorist secretidentity...,Following the death of District Attorney Harve...,112.312950,LegendaryPictures WarnerBros. DCEntertainment ...,1084939099,165.0,English,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,ChristianBale MichaelCaine GaryOldman AnneHath...,HansZimmer CharlesRoven ChristopherNolan Chris...
4,Action Adventure ScienceFiction,49529,basedonnovel mars medallion spacetravel prince...,"John Carter is a war-weary, former military ca...",43.926995,WaltDisneyPictures,284139100,132.0,English,"Lost in our world, found in another.",John Carter,6.1,2124,49529,TaylorKitsch LynnCollins SamanthaMorton Willem...,AndrewStanton AndrewStanton JohnLasseter Colin...
5,Fantasy Action Adventure,559,dualidentity amnesia sandstorm loveofone'slife...,The seemingly invincible Spider-Man goes up ag...,115.699814,ColumbiaPictures LauraZiskinProductions Marvel...,890871626,139.0,English Français,The battle within.,Spider-Man 3,5.9,3576,559,TobeyMaguire KirstenDunst JamesFranco ThomasHa...,FrancineMaisler JosephM.CaraccioloJr. SamRaimi...
6,Animation Family,38757,hostage magic horse fairytale musical princess...,When the kingdom's most wanted-and most charmi...,48.681969,WaltDisneyPictures WaltDisneyAnimationStudios,591794936,100.0,English,They're taking adventure to new lengths.,Tangled,7.4,3330,38757,ZacharyLevi MandyMoore DonnaMurphy RonPerlman ...,JohnLasseter JacobGrimm WilhelmGrimm JohnKahrs...
7,Action Adventure ScienceFiction,99861,marvelcomic sequel superhero basedoncomicbook ...,When Tony Stark tries to jumpstart a dormant p...,134.279229,MarvelStudios PrimeFocus RevolutionSunStudios,1405403694,141.0,English,A New Age Has Come.,Avengers: Age of Ultron,7.3,6767,99861,RobertDowneyJr. ChrisHemsworth MarkRuffalo Chr...,DannyElfman ChristopherBoyes ChristopherBoyes ...
8,Adventure Fantasy Family,767,witch magic broom schoolofwitchcraft wizardry ...,"As Harry begins his sixth year at Hogwarts, he...",98.885637,WarnerBros. HeydayFilms,933959197,153.0,English,Dark Secrets Revealed,Harry Potter and the Half-Blood Prince,7.4,5293,767,DanielRadcliffe RupertGrint EmmaWatson TomFelt...,BrunoDelbonnel StephanieMcMillan StuartCraig J...
9,Action Adventure Fantasy,209112,dccomics vigilante superhero basedoncomicbook ...,Fearing the actions of a god-like Super Hero l...,155.790452,DCComics AtlasEntertainment WarnerBros. DCEnte...,873260194,151.0,English,Justice or revenge,Batman v Superman: Dawn of Justice,5.7,7004,209112,BenAffleck HenryCavill GalGadot AmyAdams Jesse...,HansZimmer CharlesRoven ChristopherNolan EmmaT...
10,Adventure Fantasy Action ScienceFiction,1452,savingtheworld dccomics invulnerability sequel...,Superman returns to discover his 5-year absenc...,57.925623,DCComics LegendaryPictures WarnerBros. BadHatH...,391081192,154.0,English Français Deutsch,,Superman Returns,5.4,1400,1452,BrandonRouth KevinSpacey KateBosworth JamesMar...,RogerMussenden JonPeters DianeMacke GilbertAdl...
11,Adventure Action Thriller Crime,10764,killing undercover secretagent britishsecretse...,Quantum of Solace continues the adventures of ...,107.928811,EonProductions,586090727,106.0,English Español Italiano Français Deutsch,"For love, for hate, for justice, for revenge.",Quantum of Solace,6.1,2965,10764,DanielCraig OlgaKurylenko MathieuAmalric JudiD...,PaulHaggis DennisGassner IanFleming LouiseFrog...
12,Adventure Fantasy Action,58,witch fortuneteller bondage exoticisland monst...,Captain Jack Sparrow works his way out of a bl...,145.847379,WaltDisneyPictures JerryBruckheimerFilms Secon...,1065659812,151.0,English Türkçe ελληνικά 普通话,Jack is back!,Pirates of the Caribbean: Dead Man's Chest,7.0,5246,58,JohnnyDepp OrlandoBloom KeiraKnightley Stellan...,DariuszWolski GoreVerbinski JerryBruckheimer T...
13,Action Adventure Western,57201,texas horse survivor texasranger partner outla...,The Texas Rangers chase down a gang of outlaws...,49.046956,WaltDisneyPictures JerryBruckheimerFilms Infin...,89289910,149.0,English,Never Take Off the Mask,The Lone Ranger,5.9,2311,57201,JohnnyDepp ArmieHammer WilliamFichtner HelenaB...,GoreVerbinski GoreVerbinski JerryBruckheimer T...
14,Action Adventure Fantasy ScienceFiction,49521,savingtheworld dccomics superhero basedoncomic...,A young boy learns that he has extraordinary p...,99.398009,LegendaryPictures WarnerBros. DCEntertainment ...,662845518,143.0,English,You will believe that a man can fly.,Man of Steel,6.5,6359,49521,HenryCavill AmyAdams MichaelShannon KevinCostn...,HansZimmer CharlesRoven LloydPhillips Christop...
15,Adventure Family Fantasy,2454,basedonnovel fictionalplace brothersisterrelat...,One year after their incredible adventures in ...,53.978602,WaltDisney WaldenMedia StillkingFilms OzumiFil...,419651413,150.0,English,Hope has a new face.,The Chronicles of Narnia: Prince Caspian,6.3,1630,2454,BenBarnes WilliamMoseley AnnaPopplewell Skanda...,LizMullane GailStevens DavidMinkowski MatthewS...
16,ScienceFiction Action Adventure,24428,newyork shield marvelcomic superhero basedonco...,When an unexpected enemy emerges and threatens...,144.448633,ParamountPictures MarvelStudios,1519557910,143.0,English,Some assembly required.,The Avengers,7.4,11776,24428,RobertDowneyJr. ChrisEvans MarkRuffalo ChrisHe...,AlanSilvestri ChristopherBoyes ChristopherBoye...
17,Adventure Action Fantasy,1865,sea captain mutiny sword primeminister sailing...,Captain Jack Sparrow crosses paths with a woma...,135.413856,WaltDisneyPictures JerryBruckheimerFilms Movin...,1045713802,136.0,English Español,Live Forever Or Die Trying.,Pirates of the Caribbean: On Stranger Tides,6.4,4948,1865,JohnnyDepp PenélopeCruz IanMcShane KevinMcNall...,DariuszWolski JerryBruckheimer TedElliott Terr...
18,Action Comedy ScienceFiction,41154,timetravel timemachine alien fictionalgovernme...,Agents J (Will Smith) and K (Tommy Lee Jones) ...,52.035179,AmblinEntertainment MediaMagikEntertainment Im...,624026776,106.0,English,They are back... in time.,Men in Black 3,6.2,4160,41154,WillSmith TommyLeeJones JoshBrolin MichaelStuh...,StevenSpielberg DannyElfman EllenChenoweth Wal...
19,Action Adventure Fantasy,122917,corruption elves dwarves orcs middle-earth(tol...,Immediately after the events of The Desolation...,120.965743,WingNutFilms NewLineCinema WarnerBros.Pictures...,956019788,144.0,English,Witness the defining chapter of the Middle-Ear...,The Hobbit: The Battle of the Five Armies,7.1,4760,122917,MartinFreeman IanMcKellen RichardArmitage KenS...,HowardShore ChristopherBoyes PeterJackson Pete...

In [361]:
## budget, original_language, original_title, status, movie_id, production_countries

In [362]:
df.drop(columns=['movie_id'], inplace=True)

In [363]:
df.head(20)

,genres,id,keywords,overview,popularity,production_companies,revenue,runtime,spoken_languages,tagline,title,vote_average,vote_count,cast,crew
0,Action Adventure Fantasy ScienceFiction,19995,cultureclash future spacewar spacecolony socie...,"In the 22nd century, a paraplegic Marine is di...",150.437577,IngeniousFilmPartners TwentiethCenturyFoxFilmC...,2787965087,162.0,English Español,Enter the World of Pandora.,Avatar,7.2,11800,SamWorthington ZoeSaldana SigourneyWeaver Step...,StephenE.Rivkin RickCarter ChristopherBoyes Ch...
1,Adventure Fantasy Action,285,ocean drugabuse exoticisland eastindiatradingc...,"Captain Barbossa, long believed to be dead, ha...",139.082615,WaltDisneyPictures JerryBruckheimerFilms Secon...,961000000,169.0,English,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,JohnnyDepp OrlandoBloom KeiraKnightley Stellan...,DariuszWolski GoreVerbinski JerryBruckheimer T...
2,Action Adventure Crime,206647,spy basedonnovel secretagent sequel mi6 britis...,A cryptic message from Bond’s past sends him o...,107.376788,ColumbiaPictures Danjaq B24,880674609,148.0,Français English Español Italiano Deutsch,A Plan No One Escapes,Spectre,6.3,4466,DanielCraig ChristophWaltz LéaSeydoux RalphFie...,ThomasNewman SamMendes AnnaPinnock JohnLogan J...
3,Action Crime Drama Thriller,49026,dccomics crimefighter terrorist secretidentity...,Following the death of District Attorney Harve...,112.312950,LegendaryPictures WarnerBros. DCEntertainment ...,1084939099,165.0,English,The Legend Ends,The Dark Knight Rises,7.6,9106,ChristianBale MichaelCaine GaryOldman AnneHath...,HansZimmer CharlesRoven ChristopherNolan Chris...
4,Action Adventure ScienceFiction,49529,basedonnovel mars medallion spacetravel prince...,"John Carter is a war-weary, former military ca...",43.926995,WaltDisneyPictures,284139100,132.0,English,"Lost in our world, found in another.",John Carter,6.1,2124,TaylorKitsch LynnCollins SamanthaMorton Willem...,AndrewStanton AndrewStanton JohnLasseter Colin...
5,Fantasy Action Adventure,559,dualidentity amnesia sandstorm loveofone'slife...,The seemingly invincible Spider-Man goes up ag...,115.699814,ColumbiaPictures LauraZiskinProductions Marvel...,890871626,139.0,English Français,The battle within.,Spider-Man 3,5.9,3576,TobeyMaguire KirstenDunst JamesFranco ThomasHa...,FrancineMaisler JosephM.CaraccioloJr. SamRaimi...
6,Animation Family,38757,hostage magic horse fairytale musical princess...,When the kingdom's most wanted-and most charmi...,48.681969,WaltDisneyPictures WaltDisneyAnimationStudios,591794936,100.0,English,They're taking adventure to new lengths.,Tangled,7.4,3330,ZacharyLevi MandyMoore DonnaMurphy RonPerlman ...,JohnLasseter JacobGrimm WilhelmGrimm JohnKahrs...
7,Action Adventure ScienceFiction,99861,marvelcomic sequel superhero basedoncomicbook ...,When Tony Stark tries to jumpstart a dormant p...,134.279229,MarvelStudios PrimeFocus RevolutionSunStudios,1405403694,141.0,English,A New Age Has Come.,Avengers: Age of Ultron,7.3,6767,RobertDowneyJr. ChrisHemsworth MarkRuffalo Chr...,DannyElfman ChristopherBoyes ChristopherBoyes ...
8,Adventure Fantasy Family,767,witch magic broom schoolofwitchcraft wizardry ...,"As Harry begins his sixth year at Hogwarts, he...",98.885637,WarnerBros. HeydayFilms,933959197,153.0,English,Dark Secrets Revealed,Harry Potter and the Half-Blood Prince,7.4,5293,DanielRadcliffe RupertGrint EmmaWatson TomFelt...,BrunoDelbonnel StephanieMcMillan StuartCraig J...
9,Action Adventure Fantasy,209112,dccomics vigilante superhero basedoncomicbook ...,Fearing the actions of a god-like Super Hero l...,155.790452,DCComics AtlasEntertainment WarnerBros. DCEnte...,873260194,151.0,English,Justice or revenge,Batman v Superman: Dawn of Justice,5.7,7004,BenAffleck HenryCavill GalGadot AmyAdams Jesse...,HansZimmer CharlesRoven ChristopherNolan EmmaT...
10,Adventure Fantasy Action ScienceFiction,1452,savingtheworld dccomics invulnerability sequel...,Superman returns to discover his 5-year absenc...,57.925623,DCComics LegendaryPictures WarnerBros. BadHatH...,391081192,154.0,English Français Deutsch,,Superman Returns,5.4,1400,BrandonRouth KevinSpacey KateBosworth JamesMar...,RogerMussenden JonPeters DianeMacke GilbertAdl...
11,Adventure Action Thriller Crime,10764,killing undercover secretagent britishsecretse...,Quantum of Solace continues the adventures of ...,107.928811,EonProductions,586090727,106.0,English Español Italiano Français Deutsch,"For love, for hate, for justice, for revenge.",Quantum of Solace,6.1,2965,DanielCraig OlgaKurylenko MathieuAmalric JudiD...,PaulHaggis DennisGassner IanFleming LouiseFrog...
12,Adventure Fantasy Action,58,witch fortuneteller bondage exoticisland monst...,Captain Jack Sparrow works his way out of a bl...,145.847379,WaltDisneyPictures JerryBruckheimerFilms Secon...,1065659812,151.0,English Türkçe ελληνικά 普通话,Jack is back!,Pirates of the Caribbean: Dead Man's Chest,7.0,5246,JohnnyDepp OrlandoBloom KeiraKnightley Stellan...,DariuszWolski GoreVerbinski JerryBruckheimer T...
13,Action Adventure Western,57201,texas horse survivor texasranger partner outla...,The Texas Rangers chase down a gang of outlaws...,49.046956,WaltDisneyPictures JerryBruckheimerFilms Infin...,89289910,149.0,English,Never Take Off the Mask,The Lone Ranger,5.9,2311,JohnnyDepp ArmieHammer WilliamFichtner HelenaB...,GoreVerbinski GoreVerbinski JerryBruckheimer T...
14,Action Adventure Fantasy ScienceFiction,49521,savingtheworld dccomics superhero basedoncomic...,A young boy learns that he has extraordinary p...,99.398009,LegendaryPictures WarnerBros. DCEntertainment ...,662845518,143.0,English,You will believe that a man can fly.,Man of Steel,6.5,6359,HenryCavill AmyAdams MichaelShannon KevinCostn...,HansZimmer CharlesRoven LloydPhillips Christop...
15,Adventure Family Fantasy,2454,basedonnovel fictionalplace brothersisterrelat...,One year after their incredible adventures in ...,53.978602,WaltDisney WaldenMedia StillkingFilms OzumiFil...,419651413,150.0,English,Hope has a new face.,The Chronicles of Narnia: Prince Caspian,6.3,1630,BenBarnes WilliamMoseley AnnaPopplewell Skanda...,LizMullane GailStevens DavidMinkowski MatthewS...
16,ScienceFiction Action Adventure,24428,newyork shield marvelcomic superhero basedonco...,When an unexpected enemy emerges and threatens...,144.448633,ParamountPictures MarvelStudios,1519557910,143.0,English,Some assembly required.,The Avengers,7.4,11776,RobertDowneyJr. ChrisEvans MarkRuffalo ChrisHe...,AlanSilvestri ChristopherBoyes ChristopherBoye...
17,Adventure Action Fantasy,1865,sea captain mutiny sword primeminister sailing...,Captain Jack Sparrow crosses paths with a woma...,135.413856,WaltDisneyPictures JerryBruckheimerFilms Movin...,1045713802,136.0,English Español,Live Forever Or Die Trying.,Pirates of the Caribbean: On Stranger Tides,6.4,4948,JohnnyDepp PenélopeCruz IanMcShane KevinMcNall...,DariuszWolski JerryBruckheimer TedElliott Terr...
18,Action Comedy ScienceFiction,41154,timetravel timemachine alien fictionalgovernme...,Agents J (Will Smith) and K (Tommy Lee Jones) ...,52.035179,AmblinEntertainment MediaMagikEntertainment Im...,624026776,106.0,English,They are back... in time.,Men in Black 3,6.2,4160,WillSmith TommyLeeJones JoshBrolin MichaelStuh...,StevenSpielberg DannyElfman EllenChenoweth Wal...
19,Action Adventure Fantasy,122917,corruption elves dwarves orcs middle-earth(tol...,Immediately after the events of The Desolation...,120.965743,WingNutFilms NewLineCinema WarnerBros.Pictures...,956019788,144.0,English,Witness the defining chapter of the Middle-Ear...,The Hobbit: The Battle of the Five Armies,7.1,4760,MartinFreeman IanMcKellen RichardArmitage KenS...,HowardShore ChristopherBoyes PeterJackson Pete...

In [364]:
def to_lowerCase(x):
    if isinstance(x, str):
        return x.lower()
    return x

In [ ]:
df["tags"] = df["genres"] + " " + df["keywords"]+ " " + df["overview"]+ " " + df["tagline"]
# df["tags"] = df["genres"] + " " + df["keywords"]+ " " + df["overview"]+ " " + df["production_companies"]+ " " + df["spoken_languages"]+ " " + df["tagline"]+ " " + df["cast"]+ " " + df["crew"]

In [366]:
df.head(20)

,genres,id,keywords,overview,popularity,production_companies,revenue,runtime,spoken_languages,tagline,title,vote_average,vote_count,cast,crew,tags
0,Action Adventure Fantasy ScienceFiction,19995,cultureclash future spacewar spacecolony socie...,"In the 22nd century, a paraplegic Marine is di...",150.437577,IngeniousFilmPartners TwentiethCenturyFoxFilmC...,2787965087,162.0,English Español,Enter the World of Pandora.,Avatar,7.2,11800,SamWorthington ZoeSaldana SigourneyWeaver Step...,StephenE.Rivkin RickCarter ChristopherBoyes Ch...,Action Adventure Fantasy ScienceFiction cultur...
1,Adventure Fantasy Action,285,ocean drugabuse exoticisland eastindiatradingc...,"Captain Barbossa, long believed to be dead, ha...",139.082615,WaltDisneyPictures JerryBruckheimerFilms Secon...,961000000,169.0,English,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,JohnnyDepp OrlandoBloom KeiraKnightley Stellan...,DariuszWolski GoreVerbinski JerryBruckheimer T...,Adventure Fantasy Action ocean drugabuse exoti...
2,Action Adventure Crime,206647,spy basedonnovel secretagent sequel mi6 britis...,A cryptic message from Bond’s past sends him o...,107.376788,ColumbiaPictures Danjaq B24,880674609,148.0,Français English Español Italiano Deutsch,A Plan No One Escapes,Spectre,6.3,4466,DanielCraig ChristophWaltz LéaSeydoux RalphFie...,ThomasNewman SamMendes AnnaPinnock JohnLogan J...,Action Adventure Crime spy basedonnovel secret...
3,Action Crime Drama Thriller,49026,dccomics crimefighter terrorist secretidentity...,Following the death of District Attorney Harve...,112.312950,LegendaryPictures WarnerBros. DCEntertainment ...,1084939099,165.0,English,The Legend Ends,The Dark Knight Rises,7.6,9106,ChristianBale MichaelCaine GaryOldman AnneHath...,HansZimmer CharlesRoven ChristopherNolan Chris...,Action Crime Drama Thriller dccomics crimefigh...
4,Action Adventure ScienceFiction,49529,basedonnovel mars medallion spacetravel prince...,"John Carter is a war-weary, former military ca...",43.926995,WaltDisneyPictures,284139100,132.0,English,"Lost in our world, found in another.",John Carter,6.1,2124,TaylorKitsch LynnCollins SamanthaMorton Willem...,AndrewStanton AndrewStanton JohnLasseter Colin...,Action Adventure ScienceFiction basedonnovel m...
5,Fantasy Action Adventure,559,dualidentity amnesia sandstorm loveofone'slife...,The seemingly invincible Spider-Man goes up ag...,115.699814,ColumbiaPictures LauraZiskinProductions Marvel...,890871626,139.0,English Français,The battle within.,Spider-Man 3,5.9,3576,TobeyMaguire KirstenDunst JamesFranco ThomasHa...,FrancineMaisler JosephM.CaraccioloJr. SamRaimi...,Fantasy Action Adventure dualidentity amnesia ...
6,Animation Family,38757,hostage magic horse fairytale musical princess...,When the kingdom's most wanted-and most charmi...,48.681969,WaltDisneyPictures WaltDisneyAnimationStudios,591794936,100.0,English,They're taking adventure to new lengths.,Tangled,7.4,3330,ZacharyLevi MandyMoore DonnaMurphy RonPerlman ...,JohnLasseter JacobGrimm WilhelmGrimm JohnKahrs...,Animation Family hostage magic horse fairytale...
7,Action Adventure ScienceFiction,99861,marvelcomic sequel superhero basedoncomicbook ...,When Tony Stark tries to jumpstart a dormant p...,134.279229,MarvelStudios PrimeFocus RevolutionSunStudios,1405403694,141.0,English,A New Age Has Come.,Avengers: Age of Ultron,7.3,6767,RobertDowneyJr. ChrisHemsworth MarkRuffalo Chr...,DannyElfman ChristopherBoyes ChristopherBoyes ...,Action Adventure ScienceFiction marvelcomic se...
8,Adventure Fantasy Family,767,witch magic broom schoolofwitchcraft wizardry ...,"As Harry begins his sixth year at Hogwarts, he...",98.885637,WarnerBros. HeydayFilms,933959197,153.0,English,Dark Secrets Revealed,Harry Potter and the Half-Blood Prince,7.4,5293,DanielRadcliffe RupertGrint EmmaWatson TomFelt...,BrunoDelbonnel StephanieMcMillan StuartCraig J...,Adventure Fantasy Family witch magic broom sch...
9,Action Adventure Fantasy,209112,dccomics vigilante superhero basedoncomicbook ...,Fearing the actions of a god-like Super Hero l...,155.790452,DCComics AtlasEntertainment WarnerBros. DCEnte...,873260194,151.0,English,Justice or revenge,Batman v Superman: Dawn of Justice,5.7,7004,BenAffleck HenryCavill GalGadot AmyAdams Jesse...,HansZimmer CharlesRoven ChristopherNolan EmmaT...,Action Adventure Fantasy dccomics vigilante su...
10,Adventure Fantasy Action ScienceFiction,1452,savingtheworld dccomics invulnerability sequel...,Superman returns to discover his 5-year absenc...,57.925623,DCComics LegendaryPictures WarnerBros. BadHatH...,391081192,154.0,English Français Deutsch,,Superman Returns,5.4,1400,BrandonRouth KevinSpacey KateBosworth JamesMar...,RogerMussenden JonPeters DianeMacke GilbertAdl...,Adventure Fantasy Action ScienceFiction saving...
11,Adventure Action Thriller Crime,10764,killing undercover secretagent britishsecretse...,Quantum of Solace continues the adventures of ...,107.928811,EonProductions,586090727,106.0,English Español Italiano Français Deutsch,"For love, for hate, for justice, for revenge.",Quantum of Solace,6.1,2965,DanielCraig OlgaKurylenko MathieuAmalric JudiD...,PaulHaggis DennisGassner IanFleming LouiseFrog...,Adventure Action Thriller Crime killing underc...
12,Adventure Fantasy Action,58,witch fortuneteller bondage exoticisland monst...,Captain Jack Sparrow works his way out of a bl...,145.847379,WaltDisneyPictures JerryBruckheimerFilms Secon...,1065659812,151.0,English Türkçe ελληνικά 普通话,Jack is back!,Pirates of the Caribbean: Dead Man's Chest,7.0,5246,JohnnyDepp OrlandoBloom KeiraKnightley Stellan...,DariuszWolski GoreVerbinski JerryBruckheimer T...,Adventure Fantasy Action witch fortuneteller b...
13,Action Adventure Western,57201,texas horse survivor texasranger partner outla...,The Texas Rangers chase down a gang of outlaws...,49.046956,WaltDisneyPictures JerryBruckheimerFilms Infin...,89289910,149.0,English,Never Take Off the Mask,The Lone Ranger,5.9,2311,JohnnyDepp ArmieHammer WilliamFichtner HelenaB...,GoreVerbinski GoreVerbinski JerryBruckheimer T...,Action Adventure Western texas horse survivor ...
14,Action Adventure Fantasy ScienceFiction,49521,savingtheworld dccomics superhero basedoncomic...,A young boy learns that he has extraordinary p...,99.398009,LegendaryPictures WarnerBros. DCEntertainment ...,662845518,143.0,English,You will believe that a man can fly.,Man of Steel,6.5,6359,HenryCavill AmyAdams MichaelShannon KevinCostn...,HansZimmer CharlesRoven LloydPhillips Christop...,Action Adventure Fantasy ScienceFiction saving...
15,Adventure Family Fantasy,2454,basedonnovel fictionalplace brothersisterrelat...,One year after their incredible adventures in ...,53.978602,WaltDisney WaldenMedia StillkingFilms OzumiFil...,419651413,150.0,English,Hope has a new face.,The Chronicles of Narnia: Prince Caspian,6.3,1630,BenBarnes WilliamMoseley AnnaPopplewell Skanda...,LizMullane GailStevens DavidMinkowski MatthewS...,Adventure Family Fantasy basedonnovel fictiona...
16,ScienceFiction Action Adventure,24428,newyork shield marvelcomic superhero basedonco...,When an unexpected enemy emerges and threatens...,144.448633,ParamountPictures MarvelStudios,1519557910,143.0,English,Some assembly required.,The Avengers,7.4,11776,RobertDowneyJr. ChrisEvans MarkRuffalo ChrisHe...,AlanSilvestri ChristopherBoyes ChristopherBoye...,ScienceFiction Action Adventure newyork shield...
17,Adventure Action Fantasy,1865,sea captain mutiny sword primeminister sailing...,Captain Jack Sparrow crosses paths with a woma...,135.413856,WaltDisneyPictures JerryBruckheimerFilms Movin...,1045713802,136.0,English Español,Live Forever Or Die Trying.,Pirates of the Caribbean: On Stranger Tides,6.4,4948,JohnnyDepp PenélopeCruz IanMcShane KevinMcNall...,DariuszWolski JerryBruckheimer TedElliott Terr...,Adventure Action Fantasy sea captain mutiny sw...
18,Action Comedy ScienceFiction,41154,timetravel timemachine alien fictionalgovernme...,Agents J (Will Smith) and K (Tommy Lee Jones) ...,52.035179,AmblinEntertainment MediaMagikEntertainment Im...,624026776,106.0,English,They are back... in time.,Men in Black 3,6.2,4160,WillSmith TommyLeeJones JoshBrolin MichaelStuh...,StevenSpielberg DannyElfman EllenChenoweth Wal...,Action Comedy ScienceFiction timetravel timema...
19,Action Adventure Fantasy,122917,corruption elves dwarves orcs middle-earth(tol...,Immediately after the events of The Desolation...,120.965743,WingNutFilms NewLineCinema WarnerBros.Pictures...,956019788,144.0,English,Witness the defining chapter of the Middle-Ear...,The Hobbit: The Battle of the Five Armies,7.1,4760,MartinFreeman IanMcKellen RichardArmitage KenS...,HowardShore ChristopherBoyes PeterJackson Pete...,Action Adventure Fantasy corruption elves dwar...

In [367]:
df.drop(columns=['genres', 'keywords', 'overview', 'production_companies', 'spoken_languages', 'tagline', 'cast' , 'crew'], inplace=True)

In [368]:
df.head(20)

,id,popularity,revenue,runtime,title,vote_average,vote_count,tags
0,19995,150.437577,2787965087,162.0,Avatar,7.2,11800,Action Adventure Fantasy ScienceFiction cultur...
1,285,139.082615,961000000,169.0,Pirates of the Caribbean: At World's End,6.9,4500,Adventure Fantasy Action ocean drugabuse exoti...
2,206647,107.376788,880674609,148.0,Spectre,6.3,4466,Action Adventure Crime spy basedonnovel secret...
3,49026,112.312950,1084939099,165.0,The Dark Knight Rises,7.6,9106,Action Crime Drama Thriller dccomics crimefigh...
4,49529,43.926995,284139100,132.0,John Carter,6.1,2124,Action Adventure ScienceFiction basedonnovel m...
5,559,115.699814,890871626,139.0,Spider-Man 3,5.9,3576,Fantasy Action Adventure dualidentity amnesia ...
6,38757,48.681969,591794936,100.0,Tangled,7.4,3330,Animation Family hostage magic horse fairytale...
7,99861,134.279229,1405403694,141.0,Avengers: Age of Ultron,7.3,6767,Action Adventure ScienceFiction marvelcomic se...
8,767,98.885637,933959197,153.0,Harry Potter and the Half-Blood Prince,7.4,5293,Adventure Fantasy Family witch magic broom sch...
9,209112,155.790452,873260194,151.0,Batman v Superman: Dawn of Justice,5.7,7004,Action Adventure Fantasy dccomics vigilante su...
10,1452,57.925623,391081192,154.0,Superman Returns,5.4,1400,Adventure Fantasy Action ScienceFiction saving...
11,10764,107.928811,586090727,106.0,Quantum of Solace,6.1,2965,Adventure Action Thriller Crime killing underc...
12,58,145.847379,1065659812,151.0,Pirates of the Caribbean: Dead Man's Chest,7.0,5246,Adventure Fantasy Action witch fortuneteller b...
13,57201,49.046956,89289910,149.0,The Lone Ranger,5.9,2311,Action Adventure Western texas horse survivor ...
14,49521,99.398009,662845518,143.0,Man of Steel,6.5,6359,Action Adventure Fantasy ScienceFiction saving...
15,2454,53.978602,419651413,150.0,The Chronicles of Narnia: Prince Caspian,6.3,1630,Adventure Family Fantasy basedonnovel fictiona...
16,24428,144.448633,1519557910,143.0,The Avengers,7.4,11776,ScienceFiction Action Adventure newyork shield...
17,1865,135.413856,1045713802,136.0,Pirates of the Caribbean: On Stranger Tides,6.4,4948,Adventure Action Fantasy sea captain mutiny sw...
18,41154,52.035179,624026776,106.0,Men in Black 3,6.2,4160,Action Comedy ScienceFiction timetravel timema...
19,122917,120.965743,956019788,144.0,The Hobbit: The Battle of the Five Armies,7.1,4760,Action Adventure Fantasy corruption elves dwar...

In [369]:
df = df[df['vote_count'] > 500]

In [370]:
df.describe()

,id,popularity,revenue,runtime,vote_average,vote_count
count,1613.000000,1613.000000,1.613000e+03,1613.000000,1613.000000,1613.000000
mean,54565.608803,47.328311,2.040027e+08,113.442033,6.596528,1775.094234
std,83938.125543,43.847258,2.317876e+08,21.068891,0.763099,1653.461827
min,5.000000,1.551497,0.000000e+00,69.000000,4.100000,501.000000
25%,1735.000000,27.990284,6.005214e+07,98.000000,6.100000,733.000000
50%,10198.000000,37.698465,1.292661e+08,110.000000,6.600000,1157.000000
75%,70981.000000,53.114573,2.591758e+08,125.000000,7.200000,2114.000000
max,376659.000000,875.581305,2.787965e+09,238.000000,8.500000,13752.000000

In [371]:
df = df.map(to_lowerCase)

In [372]:
df.head(20)

,id,popularity,revenue,runtime,title,vote_average,vote_count,tags
0,19995,150.437577,2787965087,162.0,avatar,7.2,11800,action adventure fantasy sciencefiction cultur...
1,285,139.082615,961000000,169.0,pirates of the caribbean: at world's end,6.9,4500,adventure fantasy action ocean drugabuse exoti...
2,206647,107.376788,880674609,148.0,spectre,6.3,4466,action adventure crime spy basedonnovel secret...
3,49026,112.312950,1084939099,165.0,the dark knight rises,7.6,9106,action crime drama thriller dccomics crimefigh...
4,49529,43.926995,284139100,132.0,john carter,6.1,2124,action adventure sciencefiction basedonnovel m...
5,559,115.699814,890871626,139.0,spider-man 3,5.9,3576,fantasy action adventure dualidentity amnesia ...
6,38757,48.681969,591794936,100.0,tangled,7.4,3330,animation family hostage magic horse fairytale...
7,99861,134.279229,1405403694,141.0,avengers: age of ultron,7.3,6767,action adventure sciencefiction marvelcomic se...
8,767,98.885637,933959197,153.0,harry potter and the half-blood prince,7.4,5293,adventure fantasy family witch magic broom sch...
9,209112,155.790452,873260194,151.0,batman v superman: dawn of justice,5.7,7004,action adventure fantasy dccomics vigilante su...
10,1452,57.925623,391081192,154.0,superman returns,5.4,1400,adventure fantasy action sciencefiction saving...
11,10764,107.928811,586090727,106.0,quantum of solace,6.1,2965,adventure action thriller crime killing underc...
12,58,145.847379,1065659812,151.0,pirates of the caribbean: dead man's chest,7.0,5246,adventure fantasy action witch fortuneteller b...
13,57201,49.046956,89289910,149.0,the lone ranger,5.9,2311,action adventure western texas horse survivor ...
14,49521,99.398009,662845518,143.0,man of steel,6.5,6359,action adventure fantasy sciencefiction saving...
15,2454,53.978602,419651413,150.0,the chronicles of narnia: prince caspian,6.3,1630,adventure family fantasy basedonnovel fictiona...
16,24428,144.448633,1519557910,143.0,the avengers,7.4,11776,sciencefiction action adventure newyork shield...
17,1865,135.413856,1045713802,136.0,pirates of the caribbean: on stranger tides,6.4,4948,adventure action fantasy sea captain mutiny sw...
18,41154,52.035179,624026776,106.0,men in black 3,6.2,4160,action comedy sciencefiction timetravel timema...
19,122917,120.965743,956019788,144.0,the hobbit: the battle of the five armies,7.1,4760,action adventure fantasy corruption elves dwar...

In [373]:
df.to_csv('final.csv', index=False)

## Reccomendatoin System

In [ ]:
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [375]:
counts = CountVectorizer(stop_words='english', max_features=10000)
x = counts.fit_transform(df['tags']).toarray()

In [ ]:
similarity = cosine_similarity(x)

In [390]:
def recommended_movies(index: int):
    try:
        distances = similarity[index]
        movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:11]
        print(f"Recommendations for '{df.iloc[index].title}':")
        for i in movie_list:
            print(df.iloc[i[0]].title)
    except IndexError:
        print("Movie not found in dataset.")

In [ ]:
import pickle
pickle.dump(df, file=open('movies.pkl', mode="wb"))
pickle.dump(similarity, file=open('similarity.pkl', mode="wb"))